name: Run Crypto Bot
on:
  schedule:
    - cron: '*/15 * * * *'  # Toutes les 15 minutes
  workflow_dispatch:  # Permet un lancement manuel

jobs:
  execute-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          # Ou spécifiquement: npm install axios ccxt etc.

      - name: Run Bot
        run: node bot.js  # Remplacez par votre fichier principal
